### ISSUE TITLE
Лидерборд точка и запятая в качестве разделителя.

### ISSUE THREAD

**Issue by levchikm** [RussianNLP/RussianSuperGLUE#2]
Можете выбрать либо точку либо запятую в качестве разделителя целой и дробной части на сайте? А то у RCB результат 0 . 432, а у Diagnostic 0 , 186

Спасибо, что сделали бенчмарк!

**Comment by blinovpd** [comment]
В тему опечаток: файл ```RussianSuperGLUE/jiant-russian/jiant/tasks/tasks.py```
строка 1729 ```LiDiRus.jsonl```
А в данных этот файл скачивается с именем LiDiRuS.jsonl

**Comment by Alenush** [comment]
Спасибо большое! 
В новой версии поправили!
